timeout: 1800s # Cache misses are slow to rebuild
images:
- 'eu.gcr.io/$PROJECT_ID/radicle-server'
steps:
  - id: "Load cache"
    name: gcr.io/cloud-builders/gsutil
    entrypoint: 'bash'
    args:
    - '-c'
    - |
      source scripts/ci.sh
      load-cache

  - id: "Build deps"
    name: 'haskell:8.4.3'
    env: ['STACK_ROOT=/workspace/.stack']
    entrypoint: 'bash'
    args:
    - '-c'
    - |
      stack config set system-ghc --global true
      stack config set install-ghc --global false
      stack install stylish-haskell hlint

  - id: "Format"
    name: 'haskell:8.4.3'
    env: ['STACK_ROOT=/workspace/.stack']
    args: ['./scripts/check-fmt.sh']

  - id: "Lint"
    name: 'haskell:8.4.3'
    env: ['STACK_ROOT=/workspace/.stack']
    args: ['stack', 'exec', '--', 'hlint', '.']

  - id: "Build & Test"
    name: 'haskell:8.4.3'
    env: ['STACK_ROOT=/workspace/.stack']
    entrypoint: bash
    args:
    - '-c'
    - |
      apt-get -qq update
      apt-get -yqq install libpq-dev
      stack build --fast

      cp -a scripts/docker-build-shim.sh /usr/bin/docker
      stack image container

  - id: "Build reference document"
    waitFor:
    - "Build & Test"
    name: 'haskell:8.4.3'
    env: ['STACK_ROOT=/workspace/.stack']
    entrypoint: bash
    args:
    - '-c'
    - |
      mv docs/source/reference.rst oldref
      stack exec radicle-ref-doc
      if ! (diff oldref docs/source/reference.rst); then
        echo "Reference docs are not checked in"
        exit 1
      fi

  - id: "Build radicle-server image"
    waitFor:
    - "Build & Test"
    name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'eu.gcr.io/$PROJECT_ID/radicle-server', './images/radicle-server' ]

  - id: "Save cache"
    waitFor:
    - "Build & Test"
    name: gcr.io/cloud-builders/gsutil
    entrypoint: 'bash'
    args:
    - '-c'
    - |
      source scripts/ci.sh
      save-cache
