name: radicle
version: '0.0.0'
author: Monadic <team@monadic.xyz>
maintainer: Monadic <team@monadic.xyz>
license: MIT
git: oscoin/radicle
extra-source-files:
- README.md
- ChangeLog.md

dependencies:
- base >=4 && <5
- protolude
ghc-options:
  -Wall -Wcompat -Wincomplete-record-updates -Wincomplete-uni-patterns -Wredundant-constraints

data-files:
- rad/**/*.rad

library:
  source-dirs: src
  dependencies:
  - aeson
  - ansi-terminal
  - bytestring
  - containers
  - cryptonite
  - directory
  - filepath
  - generics-eot
  - haskeline
  - http-client
  - ipld-cid
  - megaparsec
  - microlens
  - mtl
  - pointed
  - prettyprinter
  - prettyprinter-ansi-terminal
  - process
  - safe-exceptions
  - scientific
  - serialise
  - servant
  - servant-client
  - template-haskell
  - text
  - time
  - unordered-containers
  - uuid
  - wreq

tests:
  spec:
    main: Main.hs
    source-dirs:
    - test/spec
    ghc-options: -threaded
    dependencies:
    - radicle
    - containers
    - cryptonite
    - directory
    - filemanip
    - interpolate
    - megaparsec
    - process
    - QuickCheck
    - quickcheck-instances
    - scientific
    - serialise
    - string-qq
    - tasty
    - tasty-discover
    - tasty-hunit
    - tasty-quickcheck
    - text
    - time
  doctest:
    main: Main.hs
    source-dirs:
    - test/docs
    ghc-options: -threaded
    dependencies:
    - doctest
    - Glob
    - hpack

executables:
  radicle:
    main: RadicleExe.hs
    source-dirs: exe
    other-modules: []
    dependencies:
    - radicle
    - bytestring
    - directory
    - optparse-applicative
    when:
      - condition: impl(ghcjs)
        buildable: false
    ghc-options: -main-is RadicleExe -O3 -threaded

  radicle-server:
    main: Server.hs
    source-dirs: exe
    other-modules: [Server.DB, Server.Common]
    when:
      - condition: impl(ghcjs)
        buildable: false
    dependencies:
    - radicle
    - aeson
    - containers
    - bytestring
    - optparse-applicative
    - postgresql-simple
    - servant
    - servant-server
    - text
    - warp
    - wai-extra
    - wai-cors
    ghc-options: -main-is Server -O3 -threaded

  radicle-daemon:
    main: Daemon.hs
    source-dirs: exe
    other-modules: [Server.Common]
    when:
      - condition: impl(ghcjs)
        buildable: false
    dependencies:
    - radicle
    - aeson
    - optparse-applicative
    - servant-server
    - text
    - warp
    ghc-options: -main-is Daemon -O3 -threaded

  radicle-client-ghcjs:
    main: GHCJS.hs
    source-dirs: exe
    other-modules: []
    dependencies:
    - radicle
    - ghcjs-base
    - exceptions
    - bytestring
    - servant
    - servant-client-ghcjs
    - http-media
    when:
      - condition: impl(ghcjs)
        then:
          buildable: true
          dependencies: ghcjs-dom
        else:
          buildable: false
    # XXX(xla): We need to remove the debug linking as it produces output js of
    # aroud 27MB.
    # We force debug linking as without it we encounter a runtime exception
    # in ghcjs due to the metadata initializer only supporting objects with up
    # to 100
    # fields: https://github.com/ghcjs/ghcjs/issues/498#issuecomment-230725647
    ghc-options: -main-is GHCJS -threaded -debug

  radicle-doc:
    main: Doc.hs
    source-dirs: exe/
    other-modules: []
    when:
      - condition: impl(ghcjs)
        buildable: false
    dependencies:
    - radicle
    - optparse-applicative
    - pandoc
    - text
    ghc-options: -main-is Doc

  radicle-ref-doc:
    main: ReferenceDoc.hs
    source-dirs: exe/
    other-modules: []
    when:
      - condition: impl(ghcjs)
        buildable: false
    dependencies:
    - radicle
    - pandoc
    - data-default
    - containers
    - text
    - yaml
    ghc-options: -main-is ReferenceDoc

  radicle-github-issues:
    main: GithubIssues.hs
    source-dirs: exe/
    other-modules: []
    when:
      - condition: impl(ghcjs)
        buildable: false
    dependencies:
    - radicle
    - containers
    - time
    - github
    - optparse-applicative
    ghc-options: -main-is GithubIssues

  radicle-benchmark:
    main: Benchmarks.hs
    source-dirs: exe/
    other-modules: []
    when:
      - condition: impl(ghcjs)
        buildable: false
    dependencies:
    - radicle
    - criterion
    ghc-options: -main-is Benchmarks

default-extensions:
- AutoDeriveTypeable
- ConstraintKinds
- DataKinds
- DefaultSignatures
- DeriveDataTypeable
- DeriveFoldable
- DeriveFunctor
- DeriveGeneric
- DeriveTraversable
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GeneralizedNewtypeDeriving
- LambdaCase
- MultiParamTypeClasses
- MultiWayIf
- NoImplicitPrelude
- OverloadedStrings
- RankNTypes
- RecordWildCards
- ScopedTypeVariables
- StandaloneDeriving
- TupleSections
- TypeFamilies
- TypeOperators
