name: radicle
version: '0.0.0'
author: Monadic <team@monadic.xyz>
maintainer: Monadic <team@monadic.xyz>
license: BSD3
git: oscoin/radicle
extra-source-files:
- README.md
- ChangeLog.md

dependencies:
- base >=4 && <5
- protolude
- containers
- deriving-compat
- haskeline
- megaparsec
- mtl
- prettyprinter
- prettyprinter-ansi-terminal
- recursion-schemes
- serialise
- scientific
- text

data-files:
- rad/config.rad
- rad/prelude.rad

library:
  source-dirs: src
  ghc-options: -Wall

tests:
  spec:
    main: Main.hs
    source-dirs:
    - test/spec
    ghc-options: -Wall -threaded
    dependencies:
    - radicle
    - directory
    - QuickCheck
    - quickcheck-instances
    - interpolate
    - safe
    - string-qq
    - tasty
    - tasty-discover
    - tasty-hunit
    - tasty-quickcheck
  doctest:
    main: Main.hs
    source-dirs:
    - test/docs
    ghc-options: -Wall -threaded
    other-modules:
    - Paths_radicle
    dependencies:
    - radicle
    - doctest
    - Glob
    - hpack

executables:
  repl:
    main: Main.hs
    source-dirs: exe/Repl
    when:
      - condition: impl(ghcjs)
        buildable: false
    dependencies:
    - radicle
    - optparse-applicative
    ghc-options: -Wall -threaded -O3 -Wcompat -Wincomplete-record-updates -Wincomplete-uni-patterns -Wredundant-constraints

  server:
    main: Server.hs
    source-dirs: exe/Server
    other-modules: API
    when:
      - condition: impl(ghcjs)
        buildable: false
    dependencies:
    - radicle
    - optparse-applicative
    - bytestring
    - servant
    - servant-server
    - http-media
    - stm-containers
    - stm
    - warp
    ghc-options: -main-is Server -Wall -O3 -threaded -Wcompat -Wincomplete-record-updates -Wincomplete-uni-patterns -Wredundant-constraints

  client:
    main: Client.hs
    source-dirs: exe/Server
    other-modules: API
    dependencies:
    - radicle
    - exceptions
    - optparse-applicative
    - bytestring
    - servant
    - http-media
    - http-client
    - servant-client
    when:
      - condition: impl(ghcjs)
        buildable: false
    ghc-options: -main-is Client -Wall -O3 -threaded -Wcompat -Wincomplete-record-updates -Wincomplete-uni-patterns -Wredundant-constraints

  client-ghcjs:
    main: GHCJS.hs
    source-dirs: exe/Server
    other-modules: API
    dependencies:
    - radicle
    - ghcjs-base
    - exceptions
    - bytestring
    - servant
    - servant-client-ghcjs
    - http-media
    when:
      - condition: impl(ghcjs)
        then:
          buildable: true
        else:
          buildable: false
    ghc-options: -main-is GHCJS -Wall -threaded -Wcompat -Wincomplete-record-updates -Wincomplete-uni-patterns -Wredundant-constraints

default-extensions:
- NoImplicitPrelude
- AutoDeriveTypeable
- ConstraintKinds
- DataKinds
- DeriveDataTypeable
- DeriveFunctor
- DeriveFoldable
- DeriveTraversable
- DeriveGeneric
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GeneralizedNewtypeDeriving
- MultiParamTypeClasses
- OverloadedStrings
- RankNTypes
- RecordWildCards
- TupleSections
- TypeFamilies
- TypeOperators
- ScopedTypeVariables
- LambdaCase
- StandaloneDeriving
