name: radicle
version: '0.0.0'
author: Monadic <team@monadic.xyz>
maintainer: Monadic <team@monadic.xyz>
license: MIT
git: oscoin/radicle
extra-source-files:
- README.md
- ChangeLog.md

dependencies:
- base >=4 && <5
- protolude
- aeson
- containers
- cryptonite
- data-default
- deriving-compat
- directory
- filepath
- generics-eot
- haskeline
- megaparsec
- mtl
- pandoc
- pointed
- prettyprinter
- prettyprinter-ansi-terminal
- recursion-schemes
- scientific
- serialise
- template-haskell
- text
- unordered-containers
- uuid
when:
 - condition: impl(ghcjs)
   dependencies: ghcjs-dom
ghc-options:
  -Wall -Wcompat -Wincomplete-record-updates -Wincomplete-uni-patterns -Wredundant-constraints

data-files:
- rad/**/*.rad

library:
  source-dirs: src

tests:
  spec:
    main: Main.hs
    source-dirs:
    - test/spec
    ghc-options: -threaded
    dependencies:
    - radicle
    - directory
    - filemanip
    - interpolate
    - QuickCheck
    - quickcheck-instances
    - safe
    - string-qq
    - tasty
    - tasty-discover
    - tasty-hunit
    - tasty-quickcheck
  doctest:
    main: Main.hs
    source-dirs:
    - test/docs
    ghc-options: -threaded
    other-modules:
    - Paths_radicle
    dependencies:
    - radicle
    - doctest
    - Glob
    - hpack

executables:
  radicle:
    main: RadicleExe.hs
    source-dirs: exe
    other-modules: API
    dependencies:
    - radicle
    - bytestring
    - exceptions
    - http-client
    - http-media
    - optparse-applicative
    - servant
    - servant-client
    when:
      - condition: impl(ghcjs)
        buildable: false
    ghc-options: -main-is RadicleExe -O3 -threaded

  radicle-server:
    main: Server.hs
    source-dirs: exe
    other-modules: [API, Server.DB]
    when:
      - condition: impl(ghcjs)
        buildable: false
    dependencies:
    - radicle
    - bytestring
    - optparse-applicative
    - postgresql-simple
    - servant
    - servant-server
    - warp
    - wai-extra
    - wai-cors
    ghc-options: -main-is Server -O3 -threaded

  radicle-client-ghcjs:
    main: GHCJS.hs
    source-dirs: exe/Server
    other-modules: API
    dependencies:
    - radicle
    - ghcjs-base
    - exceptions
    - bytestring
    - servant
    - servant-client-ghcjs
    - http-media
    when:
      - condition: impl(ghcjs)
        then:
          buildable: true
        else:
          buildable: false
    ghc-options: -main-is GHCJS -threaded

  radicle-doc:
    main: Doc.hs
    source-dirs: exe/
    other-modules: []
    when:
      - condition: impl(ghcjs)
        buildable: false
    dependencies:
    - radicle
    - optparse-applicative
    - pandoc
    ghc-options: -main-is Doc

  radicle-ref-doc:
    main: ReferenceDoc.hs
    source-dirs: exe/
    other-modules: []
    when:
      - condition: impl(ghcjs)
        buildable: false
    dependencies:
    - radicle
    - pandoc
    - data-default
    ghc-options: -main-is ReferenceDoc

default-extensions:
- AutoDeriveTypeable
- ConstraintKinds
- DataKinds
- DefaultSignatures
- DeriveDataTypeable
- DeriveFoldable
- DeriveFunctor
- DeriveGeneric
- DeriveTraversable
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GeneralizedNewtypeDeriving
- LambdaCase
- MultiParamTypeClasses
- NoImplicitPrelude
- OverloadedStrings
- RankNTypes
- RecordWildCards
- ScopedTypeVariables
- StandaloneDeriving
- TupleSections
- TypeFamilies
- TypeOperators
